application: your-application-name-here
version: 1
runtime: python27
api_version: 1
threadsafe: true

inbound_services:
- warmup

handlers:
- url: /.*
  script: ip_handler.app
  secure: always